name: Run VM tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix:
    strategy:
      matrix:
        system:
          - x86_64-linux
        test:
          - hjem-basic

    runs-on: ubuntu-latest
    steps:
      - name: "Set up QEMU support"
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: "" # no personalized self-merges tyvm.
          logger: pretty
          extra-conf: |
            experimental-features = nix-command flakes
            allow-import-from-derivation = false
            extra-platforms = aarch64-linux

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        run: nix build -L .#checks.${{ matrix.system }}.${{ matrix.test }} -v
